name: Release Spice

on:
  push:
    tags:
      - 'v*' # Trigger automatically when a tag starting with 'v' is pushed (e.g., v1.0.1)
  workflow_dispatch: # Allows you to manually trigger the workflow from the Actions tab

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]

    # This grants the workflow permission to create a GitHub Release and upload files
    permissions:
      contents: write

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies (Linux)
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install -y libarchive-tools libdbus-1-dev flatpak flatpak-builder

      - name: Install Dependencies
        run: npm install

      # Builds and publishes depending on the runner OS
      - name: Build & Publish Release (Windows)
        if: matrix.os == 'windows-latest'
        run: npx electron-builder --win --publish always
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Build & Publish Release (macOS)
        if: matrix.os == 'macos-latest'
        run: npx electron-builder --mac --publish always
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Build & Publish Release (Linux)
        if: matrix.os == 'ubuntu-latest'
        run: npx electron-builder --linux --publish always
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
